# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'key.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(375, 334)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("#centralwidget{\n"
"    border-image: url(:/img/icon.ico);\n"
"    background-repeat: no-repeat;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.loginFrame = QtWidgets.QFrame(self.centralwidget)
        self.loginFrame.setGeometry(QtCore.QRect(30, 50, 311, 230))
        self.loginFrame.setStyleSheet("#loginFrame{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    font: 75 italic 14pt \"Ubuntu\";\n"
"    border: 3px solid rgb(26, 95, 180);\n"
"    border-radius: 7px;\n"
"}")
        self.loginFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.loginFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.loginFrame.setObjectName("loginFrame")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.loginFrame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 291, 166))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.accesskey = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.accesskey.setStyleSheet("#accesskey{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    font: 75 italic 14pt \"Ubuntu\";\n"
"    border: 3px solid rgb(26, 95, 180);\n"
"    border-radius: 7px;\n"
"}")
        self.accesskey.setObjectName("accesskey")
        self.horizontalLayout.addWidget(self.accesskey)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.secretkey = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.secretkey.setStyleSheet("#secretkey{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    font: 75 italic 14pt \"Ubuntu\";\n"
"    border: 3px solid rgb(26, 95, 180);\n"
"    border-radius: 7px;\n"
"}")
        self.secretkey.setObjectName("secretkey")
        self.horizontalLayout_2.addWidget(self.secretkey)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.kuladi = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.kuladi.setStyleSheet("#kuladi{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    font: 75 italic 14pt \"Ubuntu\";\n"
"    border: 3px solid rgb(26, 95, 180);\n"
"    border-radius: 7px;\n"
"}")
        self.kuladi.setObjectName("kuladi")
        self.horizontalLayout_3.addWidget(self.kuladi)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.kulsifre = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.kulsifre.setStyleSheet("#kulsifre\n"
"{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    font: 75 italic 14pt \"Ubuntu\";\n"
"    border: 3px solid rgb(26, 95, 180);\n"
"    border-radius: 7px;\n"
"}")
        self.kulsifre.setObjectName("kulsifre")
        self.horizontalLayout_4.addWidget(self.kulsifre)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.loginLabel = QtWidgets.QLabel(self.centralwidget)
        self.loginLabel.setGeometry(QtCore.QRect(120, 30, 151, 41))
        self.loginLabel.setToolTipDuration(-1)
        self.loginLabel.setStyleSheet("#loginLabel{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    font: 75 italic 14pt \"Ubuntu\";\n"
"    border: 3px solid rgb(26, 95, 180);\n"
"    border-radius: 7px;\n"
"}")
        self.loginLabel.setObjectName("loginLabel")
        self.cikisBtn = QtWidgets.QPushButton(self.centralwidget)
        self.cikisBtn.setGeometry(QtCore.QRect(340, 10, 31, 25))
        self.cikisBtn.setStyleSheet("#cikisBtn\n"
"{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    font: 75 italic 8pt \"Ubuntu\";\n"
"    border: 3px solid rgb(26, 95, 180);\n"
"    border-radius: 7px;\n"
"}\n"
"#cikisBtn::hover\n"
"{\n"
"    color: rgb(224, 27, 36);\n"
"    background-color: rgb(255, 255, 255);\n"
"    font: 75 italic 14pt \"Ubuntu\";\n"
"    border: 3px solid rgb(26, 95, 180);\n"
"    border-radius: 7px;\n"
"}")
        self.cikisBtn.setObjectName("cikisBtn")
        self.altBtn = QtWidgets.QPushButton(self.centralwidget)
        self.altBtn.setGeometry(QtCore.QRect(300, 10, 31, 25))
        self.altBtn.setStyleSheet("#altBtn\n"
"{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    font: 75 italic 8pt \"Ubuntu\";\n"
"    border: 3px solid rgb(26, 95, 180);\n"
"    border-radius: 7px;\n"
"}\n"
"#altBtn::hover\n"
"{\n"
"    color: rgb(224, 27, 36);\n"
"    background-color: rgb(255, 255, 255);\n"
"    font: 75 italic 14pt \"Ubuntu\";\n"
"    border: 3px solid rgb(26, 95, 180);\n"
"    border-radius: 7px;\n"
"}")
        self.altBtn.setObjectName("altBtn")
        self.runLoginBtn = QtWidgets.QPushButton(self.centralwidget)
        self.runLoginBtn.setGeometry(QtCore.QRect(150, 260, 88, 41))
        self.runLoginBtn.setStyleSheet("#runLoginBtn{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(26, 95, 180);\n"
"    font: 75 italic 14pt \"Ubuntu\";\n"
"    border: 3px solid rgb(255, 255, 255);\n"
"    border-radius: 7px;\n"
"}")
        self.runLoginBtn.setObjectName("runLoginBtn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Hisse Al Sat Bot"))
        self.label.setText(_translate("MainWindow", "Access Key Giriniz : "))
        self.label_2.setText(_translate("MainWindow", "Secret Key Giriniz :"))
        self.label_3.setText(_translate("MainWindow", "Kullanıcı Adı Giriniz:"))
        self.label_4.setText(_translate("MainWindow", "Kullanıcı Şifre Giriniz:"))
        self.loginLabel.setText(_translate("MainWindow", "         LOGİN"))
        self.cikisBtn.setText(_translate("MainWindow", "X"))
        self.altBtn.setText(_translate("MainWindow", "-"))
        self.runLoginBtn.setText(_translate("MainWindow", "İLERİ"))
